;;   -*- lexical-binding: t; -*-
;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-colon
        c-electric-delete-forward
        c-electric-lt-gt
        c-electric-paren
        c-electric-semi&comma
        c-electric-slash
        c-electric-star
        c-indent-line-or-region
        dired-next-line
        dired-previous-line
        evil-insert
        evil-normal-state
        mark-sexp
        tab-to-tab-stop
        untabify
        wdired--self-insert
        ))

(setq mc/cmds-to-run-once
      '(
        end-of-buffer
        wdired-finish-edit
        ))
